trigger:
- none

variables:
  IAMGE_NAME: "azurebennie.azurecr.io/azure_devops_demo"
  TAG: "v1.0.0-$(Build.BuildId)"
  RESOURCE_GROUP: "my-rg"

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@1
      displayName: Build an image
      inputs:
        dockerfile: 'Dockerfile'
        repository: $(IAMGE_NAME)
        command: build
        tags: $(TAG)
    - task: AzureCLI@1
      inputs:
        azureSubscription: 'Azure subscription 1(c3fcc619-1d73-49dd-9e2f-42d5051a2d3a)'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr login --name azurebennie
          docker push $(IAMGE_NAME):$(TAG)

