trigger:
- none

pool:
  name: my-mac

stages:
- stage: echo
  jobs:
  - job: Echo
    steps:
    - checkout: none
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |          
          echo 'Hello world'
          pwd
          ls -l