trigger:
- main

variables:
  IAMGE_NAME: "cloudbennie/azure_devops_demo"
  TAG: "$(Build.BuildId)"

pool:
  vmImage: ubuntu-latest

stages:
# - stage: Build
#   displayName: Build image
#   jobs:
#   - job: Build
#     displayName: Build
#     steps:
#     - task: Docker@1
#       displayName: Build an image
#       inputs:
#         dockerfile: 'Dockerfile'
#         repository: $(IAMGE_NAME)
#         command: build
#         tags: $(TAG)
#     - task: Docker@2
#       displayName: Push an image
#       inputs:
#         containerRegistry: 'dockerhub-connection'
#         repository: $(IAMGE_NAME)
#         tags: $(TAG)

- stage: Deploy
  displayName: Deploy image
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    - task: AzureContainerApps@1
      inputs:
        azureSubscription: 'Azure subscription 1(c3fcc619-1d73-49dd-9e2f-42d5051a2d3a)'
        imageToDeploy: "docker.io/library/nginx:latest"
        containerAppEnvironment: “managedEnvironment-myrg-b9e6”
        containerAppName: 'azure-devops-demo'
        resourceGroup: 'my-rg'
        targetPort: '8080'
        ingress: 'external'
        containerRegistryType: 'otherContainerRegistry'
        registryServer: 'registry.hub.docker.com'
        registryUsername: '$(DOCKER_HUB_USERNAME)'
        registryPassword: '$(DOCKER_HUB_PASSWORD)'