trigger:
- main

variables:
  TAG: '$(Build.BuildId)'
  IAMGE_NAME: "cloudbennie/azure_devops_demo"

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@1
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'Dockerfile'
        imageName: ${IAMGE_NAME}:${TAG}
    - task: Docker@2
      displayName: Push an image
      inputs:
        containerRegistry: 'dockerhub-connection'
        repository: ${IAMGE_NAME}
        command: push
        tags: $(TAG)
    
