trigger:
- main

variables:
  tag: '$(Build.BuildId)'
  image_name: "cloudbennie/azure_devops_demo"

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@1
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'Dockerfile'
        imageName: ${image_name}'
        tags: $(tag)
    - task: Docker@2
      displayName: Push an image
      inputs:
        containerRegistry: 'dockerhub-connection'
        repository: '${image_name}'
        command: 'push'
        tags: $(tag)
    
