# File: azure-pipelines.yml
trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

stages:
- template: templates/checkout.yml 
  parameters:
    branch: "dev"
- template: templates/build.yml 
  parameters:
    buildcmd: "npm run build"
- template: templates/deploy.yml 
