trigger:
- main

variables:
  IAMGE_NAME: "cloudbennie/azure_devops_demo"
  TAG: "$(Build.BuildId)"

pool:
  vmImage: ubuntu-latest

stages:
# - stage: Build
#   displayName: Build image
#   jobs:
#   - job: Build
#     displayName: Build
#     steps:
#     - task: Docker@1
#       displayName: Build an image
#       inputs:
#         dockerfile: 'Dockerfile'
#         repository: $(IAMGE_NAME)
#         command: build
#         tags: $(TAG)
#     - task: Docker@2
#       displayName: Push an image
#       inputs:
#         containerRegistry: 'dockerhub-connection'
#         repository: $(IAMGE_NAME)
#         tags: $(TAG)

- stage: Deploy
  displayName: Deploy image
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo $(DOCKER_HUB_USERNAME)

    - task: AzureCLI@2
      displayName: 'Azure CLI '
      inputs:
        azureSubscription: 'Azure subscription 1(c3fcc619-1d73-49dd-9e2f-42d5051a2d3a)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          az containerapp up -n 'azure-devops-demo' -g 'my-rg' --image "cloudbennie/azure_devops_demo:13" --environment "managedEnvironment-myrg-b9e6" --ingress external --target-port 8080 --registry-username $(DOCKER_HUB_USERNAME) --registry-password $(DOCKER_HUB_PASSWORD) --registry-server hub.docker.com