trigger:
- main

variables:
  IAMGE_NAME: "cloudbennie/azure_devops_demo"
  TAG: "$(Build.BuildId)"

pool:
  vmImage: ubuntu-latest

stages:
# - stage: Build
#   displayName: Build image
#   jobs:
#   - job: Build
#     displayName: Build
#     steps:
#     - task: Docker@1
#       displayName: Build an image
#       inputs:
#         dockerfile: 'Dockerfile'
#         repository: $(IAMGE_NAME)
#         command: build
#         tags: $(TAG)
#     - task: Docker@2
#       displayName: Push an image
#       inputs:
#         containerRegistry: 'dockerhub-connection'
#         repository: $(IAMGE_NAME)
#         tags: $(TAG)

- stage: Deploy
  displayName: Deploy image
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy to Azure Container App using Docker Hub image'
      inputs:
        azureSubscription: 'Azure subscription 1(c3fcc619-1d73-49dd-9e2f-42d5051a2d3a)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Setting secrets..."
          az containerapp secret set \
            -n azure-devops-demo \
            -g my-rg \
            --secrets dockerhub-user=$(dockerHubUsername) dockerhub-pass=$(dockerHubPassword)

          echo "Updating container app..."
          az containerapp update \
            -n azure-devops-demo \
            -g my-rg \
            --image docker.io/cloudbennie/azure_devops_demo:13 \
            --registry-server registry.hub.docker.com \
            --registry-username $(dockerHubUsername) \
            --registry-password $(dockerHubPassword)
