# File: templates/build.yml

parameters:
- name: buildcmd  # defaults for any parameters that aren't specified
  default: ''

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
  - script: |
      echo "运行打包命令: ${{ parameters.buildcmd }}"
