# File: templates/checkout.yml

parameters:
- name: branch  # defaults for any parameters that aren't specified
  default: 'main'
  
stages:
- stage: Checkout
  jobs:
  - job: Checkout
    steps:
    - script: echo ${{ parameters.branch }}

